install.packages("sparklyr")
library(sparklyr)
sparklyr::spark_install()
sc<-spark_connect(master = "local")
sc <- spark_connect(master = "local", version = "2.0.0", hadoop_version="2.7")
conf <- spark_config()
conf
library(nycflights13)
install.packages("nycflights13")
install.packages(ny)
library(nycflights13)
flights <- copy_to(sc, flights, "flights")
flights_tbl <- spark_read_parquet(sc, "flights", "datainputs/nycflights13-parquet/flights")
library(dplyr)
library(sparklyr)
library(ggplot2)
flights <- copy_to(sc, flights, "flights")
View(flights)
airlines <- copy_to(sc, airlines, "airlines")
View(airlines)
src_tbls(sc)
select(flights, year:day, arr_delay, dep_delay)

